config/routes.rb
Rails.application.routes.draw do
  resources :racers
  root to: 'racers#index'

end

app/models/racer.rb
class Racer
	attr_accessor :id, :number, :first_name, :last_name, :gender, :group, :secs
	include ActiveModel::Model
	def initialize(params = {})
		@id= params[:_id].nil? ? params[:id] : params[:_id].to_s
      	@number= params[:number].to_i
      	@first_name= params[:first_name]
      	@last_name= params[:last_name]
      	@gender= params[:gender]
      	@group= params[:group]
      	@secs= params[:secs].to_i
	end
	def persisted?
		!@id.nil?
	end

	def created_at
		nil
	end

	def updated_at
		nil
	end

	def self.find(id)
	    id = BSON::ObjectId.from_string(id)
	    result = collection.find(:_id => id).first
	    return result.nil? ? nil : Racer.new(result)
  	end

  	def save
    	result = self.class.collection.insert_one(
    		number: @number, 
    		first_name: @first_name, 
            last_name: @last_name, 
            gender: @gender,
            group: @group, 
            secs: @secs)
    	@id = result.inserted_id.to_s
    end

    def update(params) 
		@number = params[:number].to_i
		@first_name = params[:first_name] 
		@last_name = params[:last_name] 
		@gender = params[:gender]
		@group = params[:group] 
		@secs = params[:secs].to_i

		params.slice!(:number, :first_name, :last_name, :gender, :group, :secs)
		self.class.collection
		    .find(:_id => BSON::ObjectId.from_string(@id))
  		    .update_one(params)
    end

    def destroy
    	self.class.collection
	        .find(_id: BSON::ObjectId.from_string(@id))
	        .delete_one
  	end

	def self.mongo_client
	  Mongoid::Clients.default
	end

	def self.collection
	  mongo_client[:racers]
  	end

  	def self.all(prototype={}, sort={}, skip=0, limit=nil) 
        results = self.collection
                  .find(prototype)
                  .sort(sort)
                  .skip(skip)
    	results = results.limit(limit) if !limit.nil?
    	return results
    end

    def self.paginate(params)
      page=(params[:page] || 1).to_i
      limit=(params[:per_page] || 30).to_i
      skip=(page-1)*limit
      sort=params[:sort] ||= {}

      racers=[]
      all({}, sort, skip, limit).each do |doc|
         racers << Racer.new(doc)
      end
      total = all({}, sort, 0, 1).count

      WillPaginate::Collection.create(page, limit, total) do |pager|
        pager.replace(racers)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/racers_controller.rb
class RacersController < ApplicationController
  before_action :set_racer, only: [:show, :edit, :update, :destroy]

  # GET /racers
  # GET /racers.json
  def index
    # @racers = Racer.all
    @racers = Racer.paginate(page:params[:page], per_page:params[:per_page])
  end

  # GET /racers/1
  # GET /racers/1.json
  def show
  end

  # GET /racers/new
  def new
    @racer = Racer.new
  end

  # GET /racers/1/edit
  def edit
  end

  # POST /racers
  # POST /racers.json
  def create
    @racer = Racer.new(racer_params)

    respond_to do |format|
      if @racer.save
        format.html { redirect_to @racer, notice: 'Racer was successfully created.' }
        format.json { render :show, status: :created, location: @racer }
      else
        format.html { render :new }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /racers/1
  # PATCH/PUT /racers/1.json
  def update
    respond_to do |format|
      if @racer.update(racer_params)
        format.html { redirect_to @racer, notice: 'Racer was successfully updated.' }
        format.json { render :show, status: :ok, location: @racer }
      else
        format.html { render :edit }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racers/1
  # DELETE /racers/1.json
  def destroy
    @racer.destroy
    respond_to do |format|
      format.html { redirect_to racers_url, notice: 'Racer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_racer
      @racer = Racer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def racer_params
      params.require(:racer).permit(:number, :first_name, :last_name, :gender, :group, :secs)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/racers_helper.rb
module RacersHelper
	def to_racer(value)
        return value.is_a?(Racer) ? value : Racer.new(value)
    end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Login dropdown", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <!--  <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li ><%= link_to 'New Racer', new_racer_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
      <ul id="login-dp" class="dropdown-menu">
        <li>
           <div class="row">
              <div class="col-md-12">
                Login via
                <div class="social-buttons">
                  <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                  <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                </div>
                                or
                 <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
                    <div class="form-group">
                       <label class="sr-only" for="exampleInputEmail2">Email address</label>
                       <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
                    </div>
                    <div class="form-group">
                       <label class="sr-only" for="exampleInputPassword2">Password</label>
                       <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
                                             <div class="help-block text-right"><a href="">Forget the password ?</a></div>
                    </div>
                    <div class="form-group">
                       <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                    </div>
                    <div class="checkbox">
                       <label>
                       <input type="checkbox"> keep me logged-in
                       </label>
                    </div>
                 </form>
              </div>
              <div class="bottom text-center">
                New here ? <a href="#"><b>Join Us</b></a>
              </div>
           </div>
        </li>
      </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Racers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/nav' %>
<%= yield %>

</body>
</html>

app/views/racers/_form.html.erb
<%= form_for(@racer) do |f| %>
  <% if @racer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@racer.errors.count, "error") %> prohibited this racer from being saved:</h2>

      <ul>
      <% @racer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="form-group">
    <%= f.label :number %><br>
    <%= f.number_field :number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :gender %><br>
    <%= f.text_field :gender, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :group %><br>
    <%= f.text_field :group, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :secs %><br>
    <%= f.number_field :secs, class: 'form-control' %>
  </div>
  
    <%= f.submit %>
  </div>
<% end %>

app/views/racers/edit.html.erb
<h1>Editing Racer</h1>

<%= render 'form' %>

<%= link_to 'Show', @racer %> |
<%= link_to 'Back', racers_path %>

app/views/racers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Racers</h1>
<div class="table-responsive">
   <table class="table table-hover">
    <thead class="thead-inverse">
      <tr>
        <th>Number</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Gender</th>
        <th>Group</th>
        <th>Secs</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @racers.each do |racer| racer=to_racer(racer) %>
        <tr>
          <td><%= racer.number %></td>
          <td><%= racer.first_name %></td>
          <td><%= racer.last_name %></td>
          <td><%= racer.gender %></td>
          <td><%= racer.group %></td>
          <td><%= racer.secs %></td>
          <td><%= link_to 'Show', racer %></td>
          <td><%= link_to 'Edit', edit_racer_path(racer) %></td>
          <td><%= link_to 'Destroy', racer, method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
</table>
</div>
<br>

  <div class="flickr_pagination">
    <%= will_paginate @racers, :container => false %>
  </div>

app/views/racers/new.html.erb
<h1>New Racer</h1>

<%= render 'form' %>

<%= link_to 'Back', racers_path %>

app/views/racers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container"> 
<p>
  <strong>Number:</strong>
  <%= @racer.number %>
</p>

<p>
  <strong>First name:</strong>
  <%= @racer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @racer.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @racer.gender %>
</p>

<p>
  <strong>Group:</strong>
  <%= @racer.group %>
</p>

<p>
  <strong>Secs:</strong>
  <%= @racer.secs %>
</p>

<%= link_to 'Edit', edit_racer_path(@racer) %> |
<%= link_to 'Back', racers_path %>
</div>